/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './pages/__root'
import { Route as ProtectedImport } from './pages/protected'
import { Route as DashbaordImport } from './pages/dashbaord'
import { Route as MentorDashImport } from './pages/mentor/dash'
import { Route as MentorMenteePageImport } from './pages/mentor-mentee/$page'
import { Route as MenteeDashImport } from './pages/mentee/dash'
import { Route as AdminDashImport } from './pages/admin/dash'

// Create Virtual Routes

const SigninLazyImport = createFileRoute('/signin')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const SigninLazyRoute = SigninLazyImport.update({
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./pages/signin.lazy').then((d) => d.Route))

const ProtectedRoute = ProtectedImport.update({
  path: '/protected',
  getParentRoute: () => rootRoute,
} as any)

const DashbaordRoute = DashbaordImport.update({
  path: '/dashbaord',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./pages/index.lazy').then((d) => d.Route))

const MentorDashRoute = MentorDashImport.update({
  path: '/mentor/dash',
  getParentRoute: () => rootRoute,
} as any)

const MentorMenteePageRoute = MentorMenteePageImport.update({
  path: '/mentor-mentee/$page',
  getParentRoute: () => rootRoute,
} as any)

const MenteeDashRoute = MenteeDashImport.update({
  path: '/mentee/dash',
  getParentRoute: () => rootRoute,
} as any)

const AdminDashRoute = AdminDashImport.update({
  path: '/admin/dash',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/dashbaord': {
      id: '/dashbaord'
      path: '/dashbaord'
      fullPath: '/dashbaord'
      preLoaderRoute: typeof DashbaordImport
      parentRoute: typeof rootRoute
    }
    '/protected': {
      id: '/protected'
      path: '/protected'
      fullPath: '/protected'
      preLoaderRoute: typeof ProtectedImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/dash': {
      id: '/admin/dash'
      path: '/admin/dash'
      fullPath: '/admin/dash'
      preLoaderRoute: typeof AdminDashImport
      parentRoute: typeof rootRoute
    }
    '/mentee/dash': {
      id: '/mentee/dash'
      path: '/mentee/dash'
      fullPath: '/mentee/dash'
      preLoaderRoute: typeof MenteeDashImport
      parentRoute: typeof rootRoute
    }
    '/mentor-mentee/$page': {
      id: '/mentor-mentee/$page'
      path: '/mentor-mentee/$page'
      fullPath: '/mentor-mentee/$page'
      preLoaderRoute: typeof MentorMenteePageImport
      parentRoute: typeof rootRoute
    }
    '/mentor/dash': {
      id: '/mentor/dash'
      path: '/mentor/dash'
      fullPath: '/mentor/dash'
      preLoaderRoute: typeof MentorDashImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  DashbaordRoute,
  ProtectedRoute,
  SigninLazyRoute,
  AdminDashRoute,
  MenteeDashRoute,
  MentorMenteePageRoute,
  MentorDashRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashbaord",
        "/protected",
        "/signin",
        "/admin/dash",
        "/mentee/dash",
        "/mentor-mentee/$page",
        "/mentor/dash"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/dashbaord": {
      "filePath": "dashbaord.tsx"
    },
    "/protected": {
      "filePath": "protected.tsx"
    },
    "/signin": {
      "filePath": "signin.lazy.tsx"
    },
    "/admin/dash": {
      "filePath": "admin/dash.tsx"
    },
    "/mentee/dash": {
      "filePath": "mentee/dash.tsx"
    },
    "/mentor-mentee/$page": {
      "filePath": "mentor-mentee/$page.tsx"
    },
    "/mentor/dash": {
      "filePath": "mentor/dash.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
